

### Request all credentials
GET http://localhost:5000/api/credentials HTTP/1.1
###
### Request a single credential
GET http://localhost:5000/api/credentials/MyService HTTP/1.1

### Add a new credential
###
POST http://localhost:5000/api/credentials HTTP/1.1
Content-Type: application/json

{
  "service": "Luise",
  "username": "Luise",
  "password": "Luise"
}

### Delete a credential
DELETE /api/credentials/MyService HTTP/1.1